/**
 * Utility functions
 */

function formatDate(dateStr) {
  if (!dateStr) return '-';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function formatTime(timeStr) {
  if (!timeStr) return '-';
  const [h, m] = timeStr.split(':');
  const hour = parseInt(h, 10);
  const ampm = hour >= 12 ? 'PM' : 'AM';
  const hour12 = hour % 12 || 12;
  return `${hour12}:${m} ${ampm}`;
}

function formatDateTime(dateStr) {
  if (!dateStr) return '-';
  const d = new Date(dateStr);
  return d.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}

function showToast(message, type = 'info') {
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  toast.textContent = message;
  toast.style.cssText = `
    position: fixed; bottom: 24px; right: 24px;
    padding: 12px 20px; border-radius: 8px;
    background: ${type === 'success' ? '#10b981' : type === 'error' ? '#ef4444' : '#0d9488'};
    color: white; z-index: 9999; font-size: 14px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  `;
  document.body.appendChild(toast);
  setTimeout(() => toast.remove(), 3000);
}

function validateEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

// Generate simple PDF content (for download as text/HTML - can use jsPDF for real PDF)
function generatePrescriptionPDF(prescription, patient, doctor) {
  const medicines = Array.isArray(prescription.medicines) 
    ? prescription.medicines 
    : (typeof prescription.medicines === 'string' ? JSON.parse(prescription.medicines || '[]') : []);
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head><title>Prescription - ${patient.name}</title>
    <style>
      body { font-family: Arial; max-width: 600px; margin: 40px auto; padding: 20px; }
      h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 8px; }
      .meta { color: #64748b; font-size: 14px; margin: 16px 0; }
      .medicine { padding: 8px 0; border-bottom: 1px solid #eee; }
      .footer { margin-top: 32px; font-size: 12px; color: #64748b; }
    </style>
    </head>
    <body>
      <h1>PRESCRIPTION</h1>
      <div class="meta">
        <strong>Patient:</strong> ${escapeHtml(patient.name)}<br>
        <strong>Date:</strong> ${formatDateTime(prescription.created_at)}<br>
        <strong>Doctor:</strong> ${escapeHtml(doctor?.name || 'N/A')}
      </div>
      <h3>Medicines</h3>
      ${medicines.map(m => `
        <div class="medicine">
          <strong>${escapeHtml(m.name || m.medicine || 'Unknown')}</strong> - 
          ${escapeHtml(m.dosage || m.dose || '')} ${escapeHtml(m.frequency || '')}
        </div>
      `).join('')}
      ${prescription.instructions ? `<p><strong>Instructions:</strong> ${escapeHtml(prescription.instructions)}</p>` : ''}
      ${prescription.notes ? `<p><strong>Notes:</strong> ${escapeHtml(prescription.notes)}</p>` : ''}
      <div class="footer">
        Generated by ClinicHub - ${formatDateTime(new Date())}
      </div>
    </body>
    </html>
  `;
  return html;
}

function downloadPrescriptionPDF(prescription, patient, doctor) {
  const JsPDF = (typeof jspdf !== 'undefined' && jspdf.jsPDF) ? jspdf.jsPDF : (window.jspdf && window.jspdf.jsPDF);
  if (JsPDF) {
    try {
      const doc = new JsPDF();
      const medicines = Array.isArray(prescription.medicines) 
        ? prescription.medicines 
        : (typeof prescription.medicines === 'string' ? JSON.parse(prescription.medicines || '[]') : []);
      
      doc.setFontSize(20);
      doc.setTextColor(13, 148, 136);
      doc.text('PRESCRIPTION', 20, 20);
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(`Patient: ${patient.name}`, 20, 30);
      doc.text(`Date: ${formatDateTime(prescription.created_at)}`, 20, 36);
      doc.text(`Doctor: ${doctor?.name || 'N/A'}`, 20, 42);
      doc.text('Medicines:', 20, 52);
      let y = 60;
      medicines.forEach(m => {
        doc.text(`• ${m.name || m.medicine || 'Unknown'} - ${m.dosage || m.dose || ''} ${m.frequency || ''}`, 20, y);
        y += 8;
      });
      if (prescription.instructions) {
        y += 5;
        doc.text(`Instructions: ${prescription.instructions}`, 20, y);
      }
      doc.save(`Prescription_${patient.name.replace(/\s/g, '_')}_${formatDate(prescription.created_at)}.pdf`);
      return;
    } catch (e) { /* fallback to HTML */ }
  }
  const html = generatePrescriptionPDF(prescription, patient, doctor);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Prescription_${patient.name.replace(/\s/g, '_')}_${formatDate(prescription.created_at)}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
